---
- name: Main
  hosts: servers
  become: true

  vars:
    git_user_email: "jazzbeaux59@gmail.com"
    git_user_name: "Mike Klein"

  tasks:
    - name: Common tasks
      ansible.builtin.include_tasks:
        file: tasks/common.yml
 
 # TODO: install samba on rpi-nas-xx
    - name: Install samba
      ansible.builtin.include_tasks:
        file: tasks/samba.yml
      when: inventory_hostname == "rpi-nas-01"
        