---
- name: Main
  hosts: all_servers
  become: true

  vars:
    git_user_email: "jazzbeaux59@gmail.com"
    git_user_name: "Mike Klein"

  tasks:
    - name: Common tasks
      ansible.builtin.include_tasks:
        file: tasks/common.yml

    - name: Install Vagrant and VirtualBox
      ansible.builtin.include_tasks:
        file: tasks/vagrant.yml
      when: "'ubuntu-01' in inventory_hostname"