---
- name: Main
  hosts: desktops
  become: true

  vars:
    git_user_email: "jazzbeaux59@gmail.com"
    git_user_name: "Mike Klein"

  tasks:
    - name: Common tasks
      ansible.builtin.include_tasks:
        file: tasks/common.yml
    
    - name: Install Ansible on remote hosts
      ansible.builtin.apt:  # Or apt, depending on the OS
        name: ansible
        state: present

    - name: Install VNC
      ansible.builtin.include_tasks:
        file: tasks/vnc.yml

    - name: Install VS Code
      ansible.builtin.include_tasks:
        file: tasks/vscode.yml

    - name: Install PyCharm
      ansible.builtin.include_tasks:
        file: tasks/pycharm.yml

    - name: Install Notepad++
      ansible.builtin.include_tasks:
        file: tasks/notepad++.yml

    - name: Install Kubernetes CLI
      ansible.builtin.include_tasks:
        file: tasks/kubectl.yml

    - name: Install Terraform
      ansible.builtin.include_tasks:
        file: tasks/terraform.yml

