# assure that the firewall tasks are first run on any Ubuntu target (see firewall.yml) and then install Apache.
- become: true
  block:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Start Apache service
      service:
        name: apache2
        state: started 
        enabled: true
