- name: Install Git
  apt:
    name: git
    state: present
- name: Setup git editor
  ansible.builtin.git_config:
    name: core.editor
    scope: global
    value: "{{ git_editor }}"

- name: Setup git email
  ansible.builtin.git_config:
    name: user.email
    scope: global
    value: "'{{ git_user_email }}'"

- name: Setup git name
  ansible.builtin.git_config:
    name: user.name
    scope: global
    value: "'{{ git_user_name }}'"
