- name: Update apt-get repo and cache
  become: true
  apt: update_cache=yes cache_valid_time=3600

- name: Upgrade all apt packages
  become: true
  apt: 
    upgrade: dist

- name: Install aptitude
  apt:
    name: aptitude
    state: latest
    update_cache: true

- name: Crontab - setup update and upgrade
  become: true
  cron:
    name: "Update and upgrade"
    minute: "0"
    hour: "5"
    job: "apt update -q -y && apt dist-upgrade -q -y"

- name: Create .ssh directory if it does not exist
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.ssh/"
    state: directory
    mode: '0700'

- name: copy ssh key files from local computer
  copy:
    src: ~/.ssh/
    dest: "/home/{{ ansible_user }}/.ssh/"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'