- name: install kvm packages on Debian based systems
  ansible.builtin.apt:
    name:
      - qemu-kvm
      - libvirt-daemon-system
      - libvirt-clients
      - virtinst
      - bridge-utils
      - virt-manager
    state: latest
  become: true
  tags:
    - kvm