- name: install other linux tools
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - vim 
    - curl
    - wget
    - net-tools
    - nano
    - htop
    - tree
    - jq
    - unzip
    - zip
    - libfuse2
    - build-essential