
- name: assure ssh server is installed
  become: true
  apt:
    name: openssh-server
    state: present
    update_cache: true

- name: assure ssh client is installed
  become: true
  apt:
    name: openssh-client
    state: present
    update_cache: true

- name: assure sshpass is installed
  become: true
  apt:
    name: sshpass
    state: present
    update_cache: true

- name: Update sshd_config
  become: true
  blockinfile:
    dest: "/etc/ssh/sshd_config"
    insertafter: "^Include /etc/ssh/sshd_config"
    block: |
      Protocol 2
      PasswordAuthentication no
      PermitEmptyPasswords no
      PermitRootLogin no
      MaxAuthTries 3

- name: Restart ssh service
  become: true
  service:
    name: ssh
    state: restarted
    enabled: true
