- name: Install Vagrant and VirtualBox
  ansible.builtin.apt:
    name:
      - vagrant
      - virtualbox
    state: present
  register: vagrant_installation

- name: Vagrant Plugin Installation
  ansible.builtin.command:
    cmd: vagrant plugin install {{ item }}
  loop:
    - vagrant-libvirt
