# TODO: steps to install VSCode on remote server
# from https://code.visualstudio.com/docs/setup/linux

# The easiest way to install Visual Studio Code for Debian/Ubuntu based distributions is to download and install the .deb package (64-bit), either through the graphical software center if it's available, or through the command line with:

# sudo apt install ./<file>.deb

# # If you're on an older Linux distribution, you will need to run this instead:
# # sudo dpkg -i <file>.deb
# # sudo apt-get install -f # Install dependencies

# Note

# Other binaries are also available on the VS Code download page.

# When you install the .deb package, it prompts to install the apt repository and signing key to enable auto-updating using the system's package manager.

# To automatically install the apt repository and signing key, such as on a non-interactive terminal, run the following command first:

# echo "code code/add-microsoft-repo boolean true" | sudo debconf-set-selections

# To manually install the apt repository:

#     Run the following script:

#     sudo apt-get install wget gpg
#     wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
#     sudo install -D -o root -g root -m 644 packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg
#     echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" |sudo tee /etc/apt/sources.list.d/vscode.list > /dev/null
#     rm -f packages.microsoft.gpg

# Then update the package cache and install the package using:

# sudo apt install apt-transport-https
# sudo apt update
# sudo apt install code # or code-insiders